package horserace

// ukTrackToAbbrev is a map from Track to Abbreviation
var ukTrackToAbbrev = map[string]string{
	"Aintree":         "Aint",
	"Ascot":           "Ascot",
	"Ayr":             "Ayr",
	"Bangor":          "Bang",
	"Bath":            "Bath",
	"Beverley":        "Bev",
	"Brighton":        "Brig",
	"Carlisle":        "Carl",
	"Cartmel":         "Cart",
	"Catterick":       "Catt",
	"Cheltenham":      "Chelt",
	"Chelmsford City": "ChelmC",
	"Chepstow":        "Chep",
	"Chester":         "Chest",
	"Doncaster":       "Donc",
	"Epsom":           "Epsm",
	"Exeter":          "Extr",
	"Fakenham":        "Fake",
	"Ffos Las":        "FfosL",
	"Folkstone":       "Folk",
	"Fontwell":        "Font",
	"Goodwood":        "Good",
	"Hamilton":        "Ham",
	"Haydock":         "Hayd",
	"Hereford":        "Here",
	"Hexham":          "Hex",
	"Huntingdon":      "Hunt",
	"Kelso":           "Kelso",
	"Kempton":         "Kemp",
	"Leicester":       "Leic",
	"Lingfield":       "Ling",
	"Ludlow":          "Ludl",
	"Market Rasen":    "MrktR",
	"Musselburgh":     "Muss",
	"Newbury":         "Newb",
	"Newcastle":       "Newc",
	"Newmarket":       "Newm",
	"Newton Abbot":    "Newt",
	"Nottingham":      "Nott",
	"Perth":           "Perth",
	"Plumpton":        "Plump",
	"Pontefract":      "Ponte",
	"Redcar":          "Redc",
	"Ripon":           "Ripon",
	"Salisbury":       "Salis",
	"Sandown":         "Sand",
	"Sedgefield":      "Sedge",
	"Southwell":       "Sthl",
	"Stratford":       "Strat",
	"Taunton":         "Taun",
	"Thirsk":          "Thirsk",
	"Towcester":       "Towc",
	"Uttoxeter":       "Uttox",
	"Warwick":         "Warw",
	"Wetherby":        "Weth",
	"Wincanton":       "Winc",
	"Windsor":         "Wind",
	"Wolverhampton":   "Wolv",
	"Worcester":       "Worc",
	"Yarmouth":        "Yarm",
	"York":            "York",
}

// ukAbbrevToTrack is a map from Abbreviation to Track
var ukAbbrevToTrack = map[string]string{
	"Aint":   "Aintree",
	"Ascot":  "Ascot",
	"Ayr":    "Ayr",
	"Bang":   "Bangor",
	"Bath":   "Bath",
	"Bev":    "Beverley",
	"Brig":   "Brighton",
	"Carl":   "Carlisle",
	"Cart":   "Cartmel",
	"Catt":   "Catterick",
	"Chelt":  "Cheltenham",
	"ChelmC": "Chelmsford City",
	"Chep":   "Chepstow",
	"Chest":  "Chester",
	"Donc":   "Doncaster",
	"Epsm":   "Epsom",
	"Extr":   "Exeter",
	"Fake":   "Fakenham",
	"FfosL":  "Ffos Las",
	"Folk":   "Folkstone",
	"Font":   "Fontwell",
	"Good":   "Goodwood",
	"Ham":    "Hamilton",
	"Hayd":   "Haydock",
	"Here":   "Hereford",
	"Hex":    "Hexham",
	"Hunt":   "Huntingdon",
	"Kelso":  "Kelso",
	"Kemp":   "Kempton",
	"Leic":   "Leicester",
	"Ling":   "Lingfield",
	"Ludl":   "Ludlow",
	"MrktR":  "Market Rasen",
	"Muss":   "Musselburgh",
	"Newb":   "Newbury",
	"Newc":   "Newcastle",
	"Newm":   "Newmarket",
	"Newt":   "Newton Abbot",
	"Nott":   "Nottingham",
	"Perth":  "Perth",
	"Plump":  "Plumpton",
	"Ponte":  "Pontefract",
	"Redc":   "Redcar",
	"Ripon":  "Ripon",
	"Salis":  "Salisbury",
	"Sand":   "Sandown",
	"Sedge":  "Sedgefield",
	"Sthl":   "Southwell",
	"Strat":  "Stratford",
	"Taun":   "Taunton",
	"Thirsk": "Thirsk",
	"Towc":   "Towcester",
	"Uttox":  "Uttoxeter",
	"Warw":   "Warwick",
	"Weth":   "Wetherby",
	"Winc":   "Wincanton",
	"Wind":   "Windsor",
	"Wolv":   "Wolverhampton",
	"Worc":   "Worcester",
	"Yarm":   "Yarmouth",
	"York":   "York",
}

// ireTrackToAbbrev is a map from Track to Abbreviation
var ireTrackToAbbrev = map[string]string{
	"Ballinrobe":   "Ballin",
	"Bellewstown":  "Belle",
	"Clonmel":      "Clon",
	"Cork":         "Cork",
	"Down Royal ":  "DownR",
	"Downpatrick":  "DownP",
	"Dundalk":      "Dund",
	"Fairyhouse":   "Fairy",
	"Galway":       "Gal",
	"Gowran Park":  "GowP",
	"Killarney":    "Killar",
	"Kilbeggan":    "Kilb",
	"Laytown":      "Layt",
	"Leopardstown": "Leop",
	"Limerick":     "Lim",
	"Listowel":     "List",
	"Naas":         "Naas",
	"Navan":        "Navan",
	"Punchestown":  "Punch",
	"Roscommon":    "Rosc",
	"Shelbourne":   "Shelb",
	"Sligo":        "Sligo",
	"The Curragh":  "Curr",
	"Thurles":      "Thurl",
	"Tipperary":    "Tipp",
	"Tralee":       "Tral",
	"Tramore":      "Tram",
	"Wexford":      "Wex",
}

// ireAbbrevToTrack is a map from Abbreviation to Track
var ireAbbrevToTrack = map[string]string{
	"Ballin": "Ballinrobe",
	"Belle":  "Bellewstown",
	"Clon":   "Clonmel",
	"Cork":   "Cork",
	"DownR":  "Down Royal ",
	"DownP":  "Downpatrick",
	"Dund":   "Dundalk",
	"Fairy":  "Fairyhouse",
	"Gal":    "Galway",
	"GowP":   "Gowran Park",
	"Killar": "Killarney",
	"Kilb":   "Kilbeggan",
	"Layt":   "Laytown",
	"Leop":   "Leopardstown",
	"Lim":    "Limerick",
	"List":   "Listowel",
	"Naas":   "Naas",
	"Navan":  "Navan",
	"Punch":  "Punchestown",
	"Rosc":   "Roscommon",
	"Shelb":  "Shelbourne",
	"Sligo":  "Sligo",
	"Curr":   "The Curragh",
	"Thurl":  "Thurles",
	"Tipp":   "Tipperary",
	"Tral":   "Tralee",
	"Tram":   "Tramore",
	"Wex":    "Wexford",
}
